version: "3.8"
services:
  backend:
    container_name: vibegopher-backend-dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresql-dev
    env_file:
      - config/development.conf

  postgresql-dev:
    container_name: vibegopher-postgresql-dev1
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    env_file:
      - config/development.conf

  atlas-dev:
    image: arigaio/atlas:latest
    volumes:
      - ./atlas.hcl:/work/atlas.hcl
      - ./schema.sql:/work/schema.sql
      - ./atlas-migrations:/work/atlas-migrations
    working_dir: /work
    depends_on:
      - postgresql-dev
    environment:
      - ATLAS_CONFIG_FILE=/work/atlas.hcl

volumes:
  postgres_dev_data:
