# Start from the same base image
FROM golang:1.24-bookworm

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Run the tests
CMD ["go", "test", "./...", "-v", "-cover"]
