version: "3.8"
services:
  backend:
    container_name: vibegopher-backend-dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresql-dev
    env_file:
      - config/development.conf

  postgresql-dev:
    container_name: vibegopher-postgresql-dev1
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    env_file:
      - config/development.conf

  atlas-dev:
    build:
      context: .
      dockerfile: Dockerfile.atlas
    volumes:
      - ./atlas.hcl:/app/atlas.hcl
      - ./schema.sql:/app/schema.sql
      - ./atlas-migrations:/app/atlas-migrations
    env_file:
      - config/development.conf
    working_dir: /app
    depends_on:
      - postgresql-dev

volumes:
  postgres_dev_data:
