# Start from the same base image
FROM golang:alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Tidy up dependencies and download them
RUN go mod tidy && go mod download

# Run the tests
CMD ["go", "test" , "./...", "-v", "-cover"]
