name: Publish Docker image to GitHub Packages
on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (backend)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Build and push Docker image (atlas)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.atlas
          push: true
          tags: ghcr.io/${{ github.repository }}:atlas-latest
